version: '3'
services:
    backend:
      build:
        context: ./backend/
      ports:
        - "8000:8080"
      environment:
        - MAILME_APP_DEBUG=0
        - MAILME_APP_HOST=0.0.0.0
      command: /app/mailmeapp
    frontend:
      build:
        context: ./frontend/
      ports:
        - "8081:80"
