version: '3'
services:
    backend:
      build:
        context: ./backend/
      container_name: mailmeapp.backend
      environment:
        - MAILME_APP_DEBUG=0
        - MAILME_APP_HOST=0.0.0.0
        - MAILME_APP_DSN=${MAILME_APP_DSN:-postgres://postgres@postgresql:5432/mailmeapp?sslmode=disable}
      command: /app/mailmeapp
      depends_on:
        - postgresql
      networks:
        - mailmeapp 
    frontend:
      build:
        context: ./frontend/
      container_name: mailmeapp.frontend
      volumes:
         - ./frontend/client/:/app
      command: yarn serve   
      networks:
        - mailmeapp 
    nginx:
      image: nginx:1.17.3-alpine
      build:
        context: ./nginx/
      container_name: mailmeapp.nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/cert/server.crt:/etc/nginx/server.crt
        - ./nginx/cert/server.key:/etc/nginx/server.key
      ports:
        - "443:443"
      depends_on:
        - backend
        - frontend
      networks:
        - mailmeapp 
    postgresql:
      image: postgres:11.5-alpine
      container_name: mailmeapp.postgres
      ports:
        - "5436:5432"
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_DB: ${POSTGRES_DB:-mailmeapp}
      volumes:
      - postgres-data:/var/lib/postgresql/data/
      networks:
        - mailmeapp 

volumes:
  postgres-data:

networks:
  mailmeapp:
