// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fbproxy.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserToken struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn            uint64   `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_620ce9fde6ee2882, []int{0}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserToken) GetExpiresIn() uint64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_620ce9fde6ee2882, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*UserToken)(nil), "rpc.UserToken")
	proto.RegisterType((*UserInfo)(nil), "rpc.UserInfo")
}

func init() { proto.RegisterFile("fbproxy.proto", fileDescriptor_620ce9fde6ee2882) }

var fileDescriptor_620ce9fde6ee2882 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4b, 0x2a, 0x28,
	0xca, 0xaf, 0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x4a,
	0xe3, 0xe2, 0x0c, 0x2d, 0x4e, 0x2d, 0x0a, 0xc9, 0xcf, 0x4e, 0xcd, 0x13, 0x12, 0xe7, 0x62, 0x2f,
	0x2d, 0x4e, 0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71,
	0x3d, 0x53, 0x84, 0x14, 0xb9, 0x78, 0x12, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xe3, 0x4b, 0x40, 0x0a,
	0x25, 0x98, 0xc0, 0xb2, 0xdc, 0x10, 0x31, 0x88, 0x5e, 0x59, 0x2e, 0xae, 0xd4, 0x8a, 0x82, 0xcc,
	0xa2, 0xd4, 0xe2, 0xf8, 0xcc, 0x3c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x4e, 0xa8, 0x88,
	0x67, 0x9e, 0x92, 0x2f, 0x17, 0x07, 0xc8, 0x1e, 0xcf, 0xbc, 0xb4, 0x7c, 0xdc, 0xd6, 0x08, 0x71,
	0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x42, 0x8d, 0x07, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13,
	0x33, 0x73, 0xc0, 0x46, 0x72, 0x06, 0x41, 0x38, 0x46, 0x25, 0x5c, 0x7c, 0x6e, 0x49, 0x01, 0x20,
	0xcf, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x19, 0x71, 0xf1, 0xb9, 0xa7, 0x96, 0x38,
	0x22, 0xb9, 0x88, 0x4f, 0xaf, 0xa8, 0x20, 0x59, 0x0f, 0xee, 0x3b, 0x29, 0x34, 0xbe, 0x12, 0x83,
	0x90, 0x1e, 0x17, 0xb7, 0x7b, 0x6a, 0x09, 0xdc, 0x5d, 0xe8, 0x1a, 0x78, 0xe1, 0x7c, 0x90, 0xb4,
	0x12, 0x43, 0x12, 0x1b, 0x38, 0xe0, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xb1, 0x37,
	0x46, 0x49, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FbProxyServiceClient is the client API for FbProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FbProxyServiceClient interface {
	GetAccessToken(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserToken, error)
	GetUserInfo(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserInfo, error)
}

type fbProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewFbProxyServiceClient(cc *grpc.ClientConn) FbProxyServiceClient {
	return &fbProxyServiceClient{cc}
}

func (c *fbProxyServiceClient) GetAccessToken(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserToken, error) {
	out := new(UserToken)
	err := c.cc.Invoke(ctx, "/rpc.FbProxyService/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fbProxyServiceClient) GetUserInfo(ctx context.Context, in *UserToken, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/rpc.FbProxyService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FbProxyServiceServer is the server API for FbProxyService service.
type FbProxyServiceServer interface {
	GetAccessToken(context.Context, *UserToken) (*UserToken, error)
	GetUserInfo(context.Context, *UserToken) (*UserInfo, error)
}

// UnimplementedFbProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFbProxyServiceServer struct {
}

func (*UnimplementedFbProxyServiceServer) GetAccessToken(ctx context.Context, req *UserToken) (*UserToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}
func (*UnimplementedFbProxyServiceServer) GetUserInfo(ctx context.Context, req *UserToken) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterFbProxyServiceServer(s *grpc.Server, srv FbProxyServiceServer) {
	s.RegisterService(&_FbProxyService_serviceDesc, srv)
}

func _FbProxyService_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FbProxyServiceServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.FbProxyService/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FbProxyServiceServer).GetAccessToken(ctx, req.(*UserToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _FbProxyService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FbProxyServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.FbProxyService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FbProxyServiceServer).GetUserInfo(ctx, req.(*UserToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _FbProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.FbProxyService",
	HandlerType: (*FbProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessToken",
			Handler:    _FbProxyService_GetAccessToken_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _FbProxyService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fbproxy.proto",
}
