// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fbproxy.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUser struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_620ce9fde6ee2882, []int{0}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NewUser) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn            uint64   `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_620ce9fde6ee2882, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *User) GetExpiresIn() uint64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func init() {
	proto.RegisterType((*NewUser)(nil), "rpc.NewUser")
	proto.RegisterType((*User)(nil), "rpc.User")
}

func init() { proto.RegisterFile("fbproxy.proto", fileDescriptor_620ce9fde6ee2882) }

var fileDescriptor_620ce9fde6ee2882 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4b, 0x2a, 0x28,
	0xca, 0xaf, 0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x72,
	0xe5, 0x62, 0xf7, 0x4b, 0x2d, 0x0f, 0x2d, 0x4e, 0x2d, 0x12, 0x12, 0xe7, 0x62, 0x2f, 0x2d, 0x4e,
	0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53,
	0x84, 0x14, 0xb9, 0x78, 0x12, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xe3, 0x4b, 0xf2, 0xb3, 0x53, 0xf3,
	0x24, 0x98, 0xc0, 0xb2, 0xdc, 0x10, 0xb1, 0x10, 0x90, 0x90, 0x52, 0x22, 0x17, 0x0b, 0xa5, 0x66,
	0x08, 0xc9, 0x72, 0x71, 0xa5, 0x56, 0x14, 0x64, 0x16, 0xa5, 0x16, 0xc7, 0x67, 0xe6, 0x49, 0x30,
	0x2b, 0x30, 0x6a, 0xb0, 0x04, 0x71, 0x42, 0x45, 0x3c, 0xf3, 0x8c, 0x6c, 0xb9, 0xf8, 0xdc, 0x92,
	0x02, 0x40, 0xee, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xd2, 0xe6, 0xe2, 0x73, 0x4f,
	0x2d, 0x71, 0x44, 0x32, 0x82, 0x47, 0xaf, 0xa8, 0x20, 0x59, 0x0f, 0xea, 0x21, 0x29, 0x4e, 0x30,
	0x0f, 0xc4, 0x54, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb5,
	0xfa, 0x54, 0x74, 0x05, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FbProxyServiceClient is the client API for FbProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FbProxyServiceClient interface {
	GetAccessToken(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type fbProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewFbProxyServiceClient(cc *grpc.ClientConn) FbProxyServiceClient {
	return &fbProxyServiceClient{cc}
}

func (c *fbProxyServiceClient) GetAccessToken(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/rpc.FbProxyService/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FbProxyServiceServer is the server API for FbProxyService service.
type FbProxyServiceServer interface {
	GetAccessToken(context.Context, *NewUser) (*User, error)
}

// UnimplementedFbProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFbProxyServiceServer struct {
}

func (*UnimplementedFbProxyServiceServer) GetAccessToken(ctx context.Context, req *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}

func RegisterFbProxyServiceServer(s *grpc.Server, srv FbProxyServiceServer) {
	s.RegisterService(&_FbProxyService_serviceDesc, srv)
}

func _FbProxyService_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FbProxyServiceServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.FbProxyService/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FbProxyServiceServer).GetAccessToken(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _FbProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.FbProxyService",
	HandlerType: (*FbProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessToken",
			Handler:    _FbProxyService_GetAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fbproxy.proto",
}
