// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twproxy.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfoRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessSecret         string   `protobuf:"bytes,2,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	TwitterId            string   `protobuf:"bytes,3,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	ScreenName           string   `protobuf:"bytes,4,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{0}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserInfoRequest) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

func (m *UserInfoRequest) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *UserInfoRequest) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

type UserInfo struct {
	TwitterId            string   `protobuf:"bytes,1,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ScreenName           string   `protobuf:"bytes,4,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ProfileImageUrl      string   `protobuf:"bytes,5,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *UserInfo) GetProfileImageUrl() string {
	if m != nil {
		return m.ProfileImageUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfoRequest)(nil), "rpc.UserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "rpc.UserInfo")
}

func init() { proto.RegisterFile("twproxy.proto", fileDescriptor_d18216394e4bf04e) }

var fileDescriptor_d18216394e4bf04e = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x09, 0x6d, 0x11, 0xbd, 0x12, 0x2a, 0xac, 0x0e, 0x16, 0x12, 0x02, 0xc2, 0x82, 0x18,
	0x32, 0x00, 0x9f, 0x01, 0x94, 0x05, 0xa1, 0xfe, 0x99, 0x2d, 0xe3, 0x5e, 0x91, 0x45, 0x12, 0x9b,
	0xb3, 0x4b, 0xe0, 0xa3, 0xb0, 0xf1, 0x51, 0x51, 0x1c, 0x83, 0x44, 0x16, 0x36, 0xfb, 0x77, 0xcf,
	0xef, 0x9e, 0x9e, 0x21, 0xf5, 0x8d, 0x25, 0xf3, 0xfe, 0x91, 0x5b, 0x32, 0xde, 0xb0, 0x01, 0x59,
	0x95, 0x7d, 0x26, 0x30, 0x5d, 0x39, 0xa4, 0xa2, 0xde, 0x98, 0x39, 0xbe, 0x6e, 0xd1, 0x79, 0x76,
	0x0e, 0x07, 0x52, 0x29, 0x74, 0x4e, 0x78, 0xf3, 0x82, 0x35, 0x4f, 0xce, 0x92, 0xcb, 0xf1, 0x7c,
	0xd2, 0xb1, 0x65, 0x8b, 0xd8, 0x05, 0xa4, 0x51, 0xe2, 0x50, 0x11, 0x7a, 0xbe, 0x1b, 0x34, 0xf1,
	0xdd, 0x22, 0x30, 0x76, 0x02, 0xe0, 0x1b, 0xed, 0x3d, 0x92, 0xd0, 0x6b, 0x3e, 0x08, 0x8a, 0x71,
	0x24, 0xc5, 0x9a, 0x9d, 0xc2, 0xc4, 0x29, 0x42, 0xac, 0x45, 0x2d, 0x2b, 0xe4, 0xc3, 0x30, 0x87,
	0x0e, 0x3d, 0xc8, 0x0a, 0xb3, 0xaf, 0x04, 0xf6, 0x7f, 0xb2, 0xf5, 0xcc, 0x92, 0xbe, 0x19, 0x83,
	0x61, 0x70, 0xe9, 0x72, 0x84, 0x33, 0x9b, 0xc1, 0x08, 0x2b, 0xa9, 0xcb, 0xb8, 0xba, 0xbb, 0xfc,
	0xbb, 0x96, 0x5d, 0xc1, 0x91, 0x25, 0xb3, 0xd1, 0x25, 0x0a, 0x5d, 0xc9, 0x67, 0x14, 0x5b, 0x2a,
	0xf9, 0x28, 0xc8, 0xa6, 0x71, 0x50, 0xb4, 0x7c, 0x45, 0xe5, 0xf5, 0x1d, 0x1c, 0x2e, 0x9b, 0xc7,
	0xb6, 0xd4, 0x05, 0xd2, 0x9b, 0x56, 0xc8, 0x6e, 0x61, 0x72, 0x8f, 0xfe, 0x37, 0xf6, 0x2c, 0x27,
	0xab, 0xf2, 0x5e, 0xc3, 0xc7, 0xe9, 0x1f, 0x9a, 0xed, 0x3c, 0xed, 0x85, 0x2f, 0xb9, 0xf9, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x85, 0x72, 0xf9, 0x00, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwProxyServiceClient is the client API for TwProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwProxyServiceClient interface {
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
}

type twProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewTwProxyServiceClient(cc *grpc.ClientConn) TwProxyServiceClient {
	return &twProxyServiceClient{cc}
}

func (c *twProxyServiceClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/rpc.TwProxyService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwProxyServiceServer is the server API for TwProxyService service.
type TwProxyServiceServer interface {
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfo, error)
}

// UnimplementedTwProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTwProxyServiceServer struct {
}

func (*UnimplementedTwProxyServiceServer) GetUserInfo(ctx context.Context, req *UserInfoRequest) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}

func RegisterTwProxyServiceServer(s *grpc.Server, srv TwProxyServiceServer) {
	s.RegisterService(&_TwProxyService_serviceDesc, srv)
}

func _TwProxyService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwProxyServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.TwProxyService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwProxyServiceServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.TwProxyService",
	HandlerType: (*TwProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _TwProxyService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twproxy.proto",
}
