// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twproxy.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfoRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessSecret         string   `protobuf:"bytes,2,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	TwitterId            string   `protobuf:"bytes,3,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	ScreenName           string   `protobuf:"bytes,4,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{0}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserInfoRequest) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

func (m *UserInfoRequest) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *UserInfoRequest) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

type UserInfo struct {
	TwitterId            string   `protobuf:"bytes,1,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ScreenName           string   `protobuf:"bytes,4,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ProfileImageUrl      string   `protobuf:"bytes,5,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *UserInfo) GetProfileImageUrl() string {
	if m != nil {
		return m.ProfileImageUrl
	}
	return ""
}

type UserSearchRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessSecret         string   `protobuf:"bytes,2,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	TwitterId            string   `protobuf:"bytes,3,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchRequest) Reset()         { *m = UserSearchRequest{} }
func (m *UserSearchRequest) String() string { return proto.CompactTextString(m) }
func (*UserSearchRequest) ProtoMessage()    {}
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{2}
}

func (m *UserSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchRequest.Unmarshal(m, b)
}
func (m *UserSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchRequest.Marshal(b, m, deterministic)
}
func (m *UserSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchRequest.Merge(m, src)
}
func (m *UserSearchRequest) XXX_Size() int {
	return xxx_messageInfo_UserSearchRequest.Size(m)
}
func (m *UserSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchRequest proto.InternalMessageInfo

func (m *UserSearchRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserSearchRequest) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

func (m *UserSearchRequest) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *UserSearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type UserSearchResult struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserSearchResult) Reset()         { *m = UserSearchResult{} }
func (m *UserSearchResult) String() string { return proto.CompactTextString(m) }
func (*UserSearchResult) ProtoMessage()    {}
func (*UserSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{3}
}

func (m *UserSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchResult.Unmarshal(m, b)
}
func (m *UserSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchResult.Marshal(b, m, deterministic)
}
func (m *UserSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchResult.Merge(m, src)
}
func (m *UserSearchResult) XXX_Size() int {
	return xxx_messageInfo_UserSearchResult.Size(m)
}
func (m *UserSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchResult proto.InternalMessageInfo

func (m *UserSearchResult) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserTimelineRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessSecret         string   `protobuf:"bytes,2,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	TwitterId            string   `protobuf:"bytes,3,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	ScreenName           string   `protobuf:"bytes,4,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	SinceId              int64    `protobuf:"varint,5,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	Count                int64    `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTimelineRequest) Reset()         { *m = UserTimelineRequest{} }
func (m *UserTimelineRequest) String() string { return proto.CompactTextString(m) }
func (*UserTimelineRequest) ProtoMessage()    {}
func (*UserTimelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{4}
}

func (m *UserTimelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTimelineRequest.Unmarshal(m, b)
}
func (m *UserTimelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTimelineRequest.Marshal(b, m, deterministic)
}
func (m *UserTimelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTimelineRequest.Merge(m, src)
}
func (m *UserTimelineRequest) XXX_Size() int {
	return xxx_messageInfo_UserTimelineRequest.Size(m)
}
func (m *UserTimelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTimelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserTimelineRequest proto.InternalMessageInfo

func (m *UserTimelineRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserTimelineRequest) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

func (m *UserTimelineRequest) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *UserTimelineRequest) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *UserTimelineRequest) GetSinceId() int64 {
	if m != nil {
		return m.SinceId
	}
	return 0
}

func (m *UserTimelineRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Tweet struct {
	IdStr                string   `protobuf:"bytes,1,opt,name=id_str,json=idStr,proto3" json:"id_str,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	FullText             string   `protobuf:"bytes,3,opt,name=full_text,json=fullText,proto3" json:"full_text,omitempty"`
	InReplyToStatusIdStr string   `protobuf:"bytes,4,opt,name=in_reply_to_status_id_str,json=inReplyToStatusIdStr,proto3" json:"in_reply_to_status_id_str,omitempty"`
	InReplyToUserIdStr   string   `protobuf:"bytes,5,opt,name=in_reply_to_user_id_str,json=inReplyToUserIdStr,proto3" json:"in_reply_to_user_id_str,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,7,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserScreenName       string   `protobuf:"bytes,8,opt,name=user_screen_name,json=userScreenName,proto3" json:"user_screen_name,omitempty"`
	UserProfileImageUrl  string   `protobuf:"bytes,9,opt,name=user_profile_image_url,json=userProfileImageUrl,proto3" json:"user_profile_image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}
func (*Tweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{5}
}

func (m *Tweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tweet.Unmarshal(m, b)
}
func (m *Tweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tweet.Marshal(b, m, deterministic)
}
func (m *Tweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tweet.Merge(m, src)
}
func (m *Tweet) XXX_Size() int {
	return xxx_messageInfo_Tweet.Size(m)
}
func (m *Tweet) XXX_DiscardUnknown() {
	xxx_messageInfo_Tweet.DiscardUnknown(m)
}

var xxx_messageInfo_Tweet proto.InternalMessageInfo

func (m *Tweet) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func (m *Tweet) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Tweet) GetFullText() string {
	if m != nil {
		return m.FullText
	}
	return ""
}

func (m *Tweet) GetInReplyToStatusIdStr() string {
	if m != nil {
		return m.InReplyToStatusIdStr
	}
	return ""
}

func (m *Tweet) GetInReplyToUserIdStr() string {
	if m != nil {
		return m.InReplyToUserIdStr
	}
	return ""
}

func (m *Tweet) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Tweet) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Tweet) GetUserScreenName() string {
	if m != nil {
		return m.UserScreenName
	}
	return ""
}

func (m *Tweet) GetUserProfileImageUrl() string {
	if m != nil {
		return m.UserProfileImageUrl
	}
	return ""
}

type UserTimelineResponse struct {
	Tweets               []*Tweet `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTimelineResponse) Reset()         { *m = UserTimelineResponse{} }
func (m *UserTimelineResponse) String() string { return proto.CompactTextString(m) }
func (*UserTimelineResponse) ProtoMessage()    {}
func (*UserTimelineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d18216394e4bf04e, []int{6}
}

func (m *UserTimelineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTimelineResponse.Unmarshal(m, b)
}
func (m *UserTimelineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTimelineResponse.Marshal(b, m, deterministic)
}
func (m *UserTimelineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTimelineResponse.Merge(m, src)
}
func (m *UserTimelineResponse) XXX_Size() int {
	return xxx_messageInfo_UserTimelineResponse.Size(m)
}
func (m *UserTimelineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTimelineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTimelineResponse proto.InternalMessageInfo

func (m *UserTimelineResponse) GetTweets() []*Tweet {
	if m != nil {
		return m.Tweets
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfoRequest)(nil), "rpc.UserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "rpc.UserInfo")
	proto.RegisterType((*UserSearchRequest)(nil), "rpc.UserSearchRequest")
	proto.RegisterType((*UserSearchResult)(nil), "rpc.UserSearchResult")
	proto.RegisterType((*UserTimelineRequest)(nil), "rpc.UserTimelineRequest")
	proto.RegisterType((*Tweet)(nil), "rpc.Tweet")
	proto.RegisterType((*UserTimelineResponse)(nil), "rpc.UserTimelineResponse")
}

func init() { proto.RegisterFile("twproxy.proto", fileDescriptor_d18216394e4bf04e) }

var fileDescriptor_d18216394e4bf04e = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x8d, 0x9b, 0x3a, 0x7f, 0x26, 0xbf, 0x34, 0xed, 0x36, 0x6d, 0x9d, 0xfc, 0x84, 0x28, 0xee,
	0x25, 0xe2, 0x90, 0x43, 0x83, 0x54, 0x89, 0x03, 0x57, 0xc8, 0x05, 0x55, 0xb6, 0x7b, 0xb6, 0x8c,
	0x33, 0x81, 0x15, 0x8e, 0xed, 0xee, 0xae, 0x49, 0xf3, 0x2d, 0xb8, 0x72, 0xe3, 0x13, 0x21, 0xc4,
	0x27, 0x42, 0x3b, 0xbb, 0x09, 0x49, 0x8a, 0xc4, 0x0d, 0x71, 0xf3, 0xbe, 0x37, 0xb3, 0xfb, 0xe6,
	0xed, 0x5b, 0x43, 0x57, 0x2d, 0x4b, 0x51, 0x3c, 0xac, 0xc6, 0xa5, 0x28, 0x54, 0xc1, 0xea, 0xa2,
	0x4c, 0xfd, 0x2f, 0x0e, 0xf4, 0xee, 0x24, 0x8a, 0x69, 0x3e, 0x2f, 0x02, 0xbc, 0xaf, 0x50, 0x2a,
	0xf6, 0x0c, 0xfe, 0x4b, 0xd2, 0x14, 0xa5, 0x8c, 0x55, 0xf1, 0x11, 0x73, 0xcf, 0xb9, 0x74, 0x46,
	0xed, 0xa0, 0x63, 0xb0, 0x48, 0x43, 0xec, 0x0a, 0xba, 0xb6, 0x44, 0x62, 0x2a, 0x50, 0x79, 0x07,
	0x54, 0x63, 0xfb, 0x42, 0xc2, 0xd8, 0x13, 0x00, 0xb5, 0xe4, 0x4a, 0xa1, 0x88, 0xf9, 0xcc, 0xab,
	0x53, 0x45, 0xdb, 0x22, 0xd3, 0x19, 0x7b, 0x0a, 0x1d, 0x99, 0x0a, 0xc4, 0x3c, 0xce, 0x93, 0x05,
	0x7a, 0x87, 0xc4, 0x83, 0x81, 0xde, 0x26, 0x0b, 0xf4, 0xbf, 0x3a, 0xd0, 0x5a, 0x6b, 0xdb, 0xdb,
	0xcc, 0xd9, 0xdf, 0x8c, 0xc1, 0x21, 0xed, 0x62, 0x74, 0xd0, 0x37, 0xeb, 0x83, 0x8b, 0x8b, 0x84,
	0x67, 0xf6, 0x68, 0xb3, 0xf8, 0xe3, 0xb1, 0xec, 0x39, 0x9c, 0x94, 0xa2, 0x98, 0xf3, 0x0c, 0x63,
	0xbe, 0x48, 0xde, 0x63, 0x5c, 0x89, 0xcc, 0x73, 0xa9, 0xac, 0x67, 0x89, 0xa9, 0xc6, 0xef, 0x44,
	0xe6, 0x7f, 0x76, 0xe0, 0x44, 0x4b, 0x0c, 0x31, 0x11, 0xe9, 0x87, 0xbf, 0x6c, 0x60, 0x1f, 0xdc,
	0xfb, 0x0a, 0xc5, 0xca, 0xce, 0x60, 0x16, 0xfe, 0x0d, 0x1c, 0x6f, 0x2b, 0x92, 0x55, 0xa6, 0xd8,
	0x15, 0xb8, 0x95, 0x44, 0x21, 0x3d, 0xe7, 0xb2, 0x3e, 0xea, 0x5c, 0x77, 0xc7, 0xa2, 0x4c, 0xc7,
	0x9b, 0x6b, 0x37, 0x9c, 0xff, 0xcd, 0x81, 0x53, 0x8d, 0x45, 0x7c, 0x81, 0x19, 0xcf, 0xf1, 0x1f,
	0x8b, 0x03, 0x1b, 0x40, 0x4b, 0xf2, 0x3c, 0x45, 0xdd, 0xad, 0xaf, 0xa3, 0x1e, 0x34, 0x69, 0x6d,
	0x9c, 0x48, 0x8b, 0x2a, 0x57, 0x5e, 0x83, 0x70, 0xb3, 0xf0, 0x7f, 0x1c, 0x80, 0x1b, 0x2d, 0x11,
	0x15, 0x3b, 0x83, 0x06, 0x9f, 0xc5, 0x52, 0x09, 0x2b, 0xde, 0xe5, 0xb3, 0x50, 0x09, 0x1d, 0x1a,
	0x85, 0x0f, 0x6b, 0xb5, 0xf4, 0xcd, 0xfe, 0x87, 0xf6, 0xbc, 0xca, 0xb2, 0x98, 0x08, 0x23, 0xb2,
	0xa5, 0x81, 0x48, 0x93, 0x37, 0x30, 0xe0, 0x79, 0x2c, 0xb0, 0xcc, 0x56, 0xb1, 0x2a, 0x62, 0xa9,
	0x12, 0x55, 0xc9, 0xd8, 0x6e, 0x6d, 0x14, 0xf7, 0x79, 0x1e, 0x68, 0x3e, 0x2a, 0x42, 0x62, 0xa7,
	0x74, 0xd2, 0x04, 0x2e, 0xb6, 0x1b, 0xb5, 0xe1, 0xeb, 0x36, 0x93, 0x2c, 0xb6, 0x69, 0xa3, 0x6b,
	0xa1, 0xa6, 0x0b, 0x68, 0xda, 0x42, 0x9a, 0xab, 0x1d, 0x34, 0x2a, 0xe2, 0xb4, 0x46, 0x22, 0xc8,
	0xa8, 0xa6, 0xd1, 0xa8, 0x01, 0xb2, 0x69, 0x04, 0xc7, 0x44, 0x6e, 0x9b, 0xd9, 0xa2, 0x9a, 0x23,
	0x8d, 0x87, 0xbf, 0x0c, 0x9d, 0xc0, 0x39, 0x55, 0x3e, 0x4e, 0x7b, 0x9b, 0xea, 0x4f, 0x35, 0x7b,
	0xbb, 0x97, 0xf8, 0x97, 0xd0, 0xdf, 0x0d, 0x89, 0x2c, 0x8b, 0x5c, 0x22, 0xf3, 0xa1, 0xa1, 0xb4,
	0xd7, 0xeb, 0x8c, 0x01, 0x65, 0x8c, 0xec, 0x0f, 0x2c, 0x73, 0xfd, 0xdd, 0x81, 0xa3, 0x68, 0x79,
	0xab, 0xff, 0x41, 0x21, 0x8a, 0x4f, 0x3c, 0x45, 0xf6, 0x02, 0x3a, 0xaf, 0x51, 0x6d, 0x5e, 0x79,
	0x7f, 0x37, 0x99, 0x26, 0x81, 0xc3, 0xdd, 0xbc, 0xfa, 0x35, 0xf6, 0x0a, 0x3a, 0x26, 0xdf, 0x1a,
	0x93, 0xec, 0x7c, 0xc3, 0xef, 0xbc, 0xc3, 0xe1, 0xd9, 0x23, 0x5c, 0xbf, 0x06, 0xbf, 0xc6, 0xde,
	0x40, 0xcf, 0x9e, 0xba, 0x9e, 0x83, 0x79, 0x9b, 0xda, 0xbd, 0xfc, 0x0f, 0x07, 0xbf, 0x61, 0xcc,
	0xd0, 0x7e, 0xed, 0x5d, 0x83, 0xfe, 0xa5, 0x93, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x67,
	0xb5, 0xbc, 0x5c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TwProxyServiceClient is the client API for TwProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwProxyServiceClient interface {
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	SearchUsers(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserSearchResult, error)
	GetUserTimeline(ctx context.Context, in *UserTimelineRequest, opts ...grpc.CallOption) (*UserTimelineResponse, error)
}

type twProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewTwProxyServiceClient(cc *grpc.ClientConn) TwProxyServiceClient {
	return &twProxyServiceClient{cc}
}

func (c *twProxyServiceClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/rpc.TwProxyService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twProxyServiceClient) SearchUsers(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserSearchResult, error) {
	out := new(UserSearchResult)
	err := c.cc.Invoke(ctx, "/rpc.TwProxyService/SearchUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twProxyServiceClient) GetUserTimeline(ctx context.Context, in *UserTimelineRequest, opts ...grpc.CallOption) (*UserTimelineResponse, error) {
	out := new(UserTimelineResponse)
	err := c.cc.Invoke(ctx, "/rpc.TwProxyService/GetUserTimeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwProxyServiceServer is the server API for TwProxyService service.
type TwProxyServiceServer interface {
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfo, error)
	SearchUsers(context.Context, *UserSearchRequest) (*UserSearchResult, error)
	GetUserTimeline(context.Context, *UserTimelineRequest) (*UserTimelineResponse, error)
}

// UnimplementedTwProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTwProxyServiceServer struct {
}

func (*UnimplementedTwProxyServiceServer) GetUserInfo(ctx context.Context, req *UserInfoRequest) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedTwProxyServiceServer) SearchUsers(ctx context.Context, req *UserSearchRequest) (*UserSearchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsers not implemented")
}
func (*UnimplementedTwProxyServiceServer) GetUserTimeline(ctx context.Context, req *UserTimelineRequest) (*UserTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTimeline not implemented")
}

func RegisterTwProxyServiceServer(s *grpc.Server, srv TwProxyServiceServer) {
	s.RegisterService(&_TwProxyService_serviceDesc, srv)
}

func _TwProxyService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwProxyServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.TwProxyService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwProxyServiceServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwProxyService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwProxyServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.TwProxyService/SearchUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwProxyServiceServer).SearchUsers(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwProxyService_GetUserTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwProxyServiceServer).GetUserTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.TwProxyService/GetUserTimeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwProxyServiceServer).GetUserTimeline(ctx, req.(*UserTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.TwProxyService",
	HandlerType: (*TwProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _TwProxyService_GetUserInfo_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _TwProxyService_SearchUsers_Handler,
		},
		{
			MethodName: "GetUserTimeline",
			Handler:    _TwProxyService_GetUserTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twproxy.proto",
}
