// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: from, to, subject, body
func (_m *EmailSender) Send(from string, to string, subject string, body string) error {
	ret := _m.Called(from, to, subject, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(from, to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
