// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import rpc "github.com/dmtr/mail_me_all/backend/rpc"

// FbProxyServiceClient is an autogenerated mock type for the FbProxyServiceClient type
type FbProxyServiceClient struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: ctx, in, opts
func (_m *FbProxyServiceClient) GetAccessToken(ctx context.Context, in *rpc.UserToken, opts ...grpc.CallOption) (*rpc.UserToken, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *rpc.UserToken
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.UserToken, ...grpc.CallOption) *rpc.UserToken); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.UserToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rpc.UserToken, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInfo provides a mock function with given fields: ctx, in, opts
func (_m *FbProxyServiceClient) GetUserInfo(ctx context.Context, in *rpc.UserToken, opts ...grpc.CallOption) (*rpc.UserInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *rpc.UserInfo
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.UserToken, ...grpc.CallOption) *rpc.UserInfo); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.UserInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rpc.UserToken, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
